---
- name: Update and upgrade Ubuntu server
  hosts: your_ubuntu_server
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become: true

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
        dpkg_options: 'force-confnew'
      become: true
